[GN-87] feat: 입력 컴포넌트 추가
Team1-CodeIt-Sprint6/K-venture pull request #11
Opened 2024-07-31 09:10 UTC by Bersk3r

## 연관된 이슈

ex) #이슈번호, #이슈번호

## 작업 내용

이번 PR에서 작업한 내용을 간략히 설명해주세요.

- [x] 입력 컴포넌트 공통 제작
- [x] 에러 메세지 공통 컴포넌트 제작
- [x] 라벨 공통 컴포넌트 제작
- [x] 버튼 공통 컴포넌트 제작
- [x] 외부 폰트를 참조하지 못 하는 문제 해결

## 스크린샷
입력 화면 
![image](https://github.com/user-attachments/assets/98ef0062-d0b3-45ad-b0b2-5c0f711e1677)

입력 후, 유효성 문제가 발생했을 때
![image](https://github.com/user-attachments/assets/77484d44-1839-40f9-be1b-fe94a3c74152)

입력 후, 유효성 문제가 발생되지 않았을 때
![image](https://github.com/user-attachments/assets/b73fd216-b26a-4694-9d19-f79b9202d7a6)

외부 폰트가 정상적으로 불러지는 부분 확인 완료
![image](https://github.com/user-attachments/assets/5b8cbf50-3ada-4ecb-90bd-8d0d10c94286)

## 코멘트 및 논의 사항
- 테스트할만 컴포넌트 대신, 추후에 사용할 페이지에 테스트를 진행하였습니다. 
(추후, 로그인 및 회원가입 페이지 이슈 내에서 수정할 예정)
- Next.js에서 제공하는 LocalFont를 사용하면 최적화가 된다고 하여, LocalFont를 활용하여 폰트 에러를 해결하였습니다.
- 내용 중에 잘못된 부분이나, 최적화가 가능한 부분이 있다면 코멘트를 부탁드립니다.

2024-07-31 09:42 UTC, un0211 approved these changes
인풋 만들어주셔서 감사합니다! 잘 써볼게요!

2024-07-31 09:42 UTC, un0211 commented on src/components/common/Input.tsx
> +interface IInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
그냥 궁금한 점인데, IInput이라고 한 이유가 있을까요???

2024-07-31 09:42 UTC, un0211 commented on src/components/common/Input.tsx
> +const INPUT_STYLE =
global.css에 클래스로 만들어두는 것보다 이게 더 깔끔하다고 생각해서 여기에서 정의하신건가요??
input을 여기서 다 커버하면 다른데서는 쓸 일이 없으니 굳이 클래스로 안만들고 여기에서 정의해도 괜찮을 것 같긴 하네요

2024-07-31 09:42 UTC, un0211 commented on src/components/common/ErrorText.tsx
에러 텍스트도 만들어주셨네요👍

2024-07-31 09:42 UTC, un0211 commented on src/styles/globals.css
> -    @apply h-6 w-6; /* width: 24px, hegiht: 24px */
이건 송아님이 만든 부분 지우신건가요???
서로 합의가 되었나요?

2024-07-31 09:43 UTC, Bersk3r commented on src/components/common/Input.tsx
> +interface IInputProps extends React.InputHTMLAttributes<HTMLInputElement> {
인터페이스를 선언할 때 네이밍을 I가 붙어서 그렇게 만들었습니다.
괜찮은 네이밍이 있으면 말씀 부탁드립니다.

2024-07-31 12:35 UTC, soma0078 requested changes
수고하셨습니다!

2024-07-31 12:35 UTC, soma0078 commented on src/styles/globals.css
> -    @apply h-6 w-6; /* width: 24px, hegiht: 24px */
저 .icon-size 사용 중이에요ㅠ

2024-07-31 12:35 UTC, soma0078 commented on src/pages/_app.tsx
> +});
폰트 최적화 좋습니다 👍👍

2024-07-31 12:35 UTC, soma0078 commented on src/pages/login/index.tsx
> +
리액트 17버전부턴 `import React from 'react';` 생략 가능하다고 합니다!

2024-07-31 14:10 UTC, un0211 commented
참, 입력만 작업하신 게 아니라서 PR 제목 수정하면 좋을 것 같아요 (입력 관련 컴포넌트들이긴 하지만)

2024-08-01 04:48 UTC, wch2208 approved these changes

2024-08-01 04:48 UTC, wch2208 commented on src/pages/_app.tsx
> +});
와 배워갑니다!
이거 작업하셨던 기록 남겨두시면 next를 썼을 때 좋았던 경험으로 이야기하기 좋을 것 같아요

2024-08-01 04:48 UTC, wch2208 commented on src/components/common/Label.tsx
> +export default Label;
(중요도 하)
버튼도 같은 맥락인데 다른 곳에서도 일부분 변경해서 쓸 수 있게 열어두는 조치를 추가해도 좋을 것 같습니다
우리 프로젝트에 라벨이 다른 곳에 안쓰인다면 수정은 안하셔도 괜찮아요 
```
import React from 'react';

interface LabelProps extends React.LabelHTMLAttributes<HTMLLabelElement> {
  className?: string;
}

const Label: React.FC<LabelProps> = ({ htmlFor, children, className = '', ...props }) => {
  return (
    <label
      htmlFor={htmlFor}
      className={`font-kv-medium kv-text-lg ${className}`.trim()}
      {...props}
    >
      {children}
    </label>
  );
};

export default Label;
```

2024-08-01 08:50 UTC, soma0078 approved these changes

2024-08-01 11:30 UTC, Bersk3r commented
테스트

2024-08-01 11:34 UTC, Bersk3r commented
테스트2

2024-08-01 12:02 UTC, Bersk3r commented
알림 테스트

2024-08-01 12:07 UTC, Bersk3r commented
알림 테스트2

2024-08-01 12:08 UTC, Bersk3r commented
이거 이슈 코멘트입니다.

2024-08-01 12:09 UTC, Bersk3r reviewed
리뷰 코멘트를 제출할 때, 알림이 나타납니다.

2024-08-01 12:09 UTC, Bersk3r commented on src/pages/_app.tsx
> +});
감사합니다.

2024-08-01 12:16 UTC, Bersk3r reviewed
테스트입니다

2024-08-01 12:16 UTC, Bersk3r commented on src/components/common/Input.tsx
> +const INPUT_STYLE =
추가 테스트

2024-08-01 12:20 UTC, Bersk3r reviewed
테스트입니다2

2024-08-01 12:20 UTC, Bersk3r commented on src/components/common/Input.tsx
> +const INPUT_STYLE =
추가 테스트2

2024-08-01 12:22 UTC, merged